apiVersion: v1
kind: Secret
metadata:
  name: openstad-mongo-credentials
  namespace: openstad
data:
  hostname: b3BlbnN0YWQtbW9uZ29kYi5vcGVuYW1zdGVyZGFtLnN2Yy5jbHVzdGVyLmxvY2Fs
  hostport: BASE64ENCODED=
  password: BASE64ENCODED=
  username: BASE64ENCODED=
