apiVersion: v1
kind: Secret
metadata:
  name: openstad-mongo-credentials
  namespace: {{ .Release.Namespace }}
data:
  hostname: BASE64ENCODED=
  hostport: BASE64ENCODED=
  password: BASE64ENCODED=
  username: BASE64ENCODED=
