apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.adminer.deployment.name }}
  namespace: {{ .Values.adminer.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.adminer.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.adminer.label }}
    spec:
      containers:
      - name: {{ .Values.adminer.deploymentContainer.name }}
        image: {{ .Values.adminer.deploymentContainer.image }}
        ports:
            - name: http
              containerPort: {{ .Values.adminer.deploymentContainer.port }}
        env:
          # DB Reference
          - name: ADMINER_DEFAULT_SERVER
            value: "openstad-mysql"
