apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openstad-ingress
spec:
  rules:
  - host: www.openstad.softwaredepartment.net
    http:
      paths:
      - backend:
          serviceName: frontend-service
          servicePort: 4444
        path: /