---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openstad.admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstad.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "openstad.admin.fullname" . }}-deployment
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.admin.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.admin.label }}
    spec:
      volumes:
        - name: certs
          secret:
            secretName: openstad-auth-certificates
      containers:
      - name: {{ template "openstad.admin.fullname" . }}
        image: {{ .Values.admin.deploymentContainer.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.admin.service.httpPort }}
            name: http
        env:
          # HOSTING
          - name: SITE_ID
            value: "1"

          - name: BASIC_AUTH_USER
            value: "user"

          - name: BASIC_AUTH_PASSWORD
            value: "pass"

          # KUBERNETES
          - name: SESSION_SECRET
            value: "1234567890123456"

          - name: SITE_API_KEY
            valueFrom:
              secretKeyRef:
                key: fixed_token
                name: openstad-auth-credentials

          - name: APP_URL
            value: https://{{ template "openstad.admin.url" . }}

          - name: API_URL
            value: https://{{ template "openstad.api.url" . }}

          - name: USER_API
            value: https://{{ template "openstad.auth.url" . }}

          - name: USER_API_CLIENT_ID_1
            valueFrom:
              secretKeyRef:
                key: client_id
                name: openstad-auth-credentials

          - name: USER_API_CLIENT_SECRET_1
            valueFrom:
              secretKeyRef:
                key: client_secret
                name: openstad-auth-credentials
          - name: USER_API_CLIENT_ID
            value: 2f2c7b3a838dcc33bdfee74137575468

          - name: USER_API_CLIENT_SECRET
            value: 1f9ffddcfb4569db413126a67edca37a


          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP

          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        resources:
{{ toYaml .Values.admin.resources | indent 12 }}
