---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "openstad.admin.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "openstad.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "openstad.admin.fullname" . }}-deployment
spec:
  replicas: {{ .Values.admin.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.admin.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.admin.label }}
    spec:
      volumes:
        - name: certs
          secret:
            secretName: openstad-auth-certificates
      containers:
      - name: {{ template "openstad.admin.fullname" . }}
        image: {{ .Values.admin.deploymentContainer.image }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.admin.service.httpPort }}
            name: http
        env:
          # HOSTING
          - name: SITE_ID
            value: "0"

          - name: BASIC_AUTH_USER
            value: "user"

          - name: BASIC_AUTH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: "PASSWORD"
                name: {{ template "openstad.admin.secret.fullname" . }}

          - name: MONGO_DB_HOST
            valueFrom:
                secretKeyRef:
                  key: "hostname"
                  name: openstad-mongo-credentials

          # KUBERNETES
          - name: SESSION_SECRET
            valueFrom:
              secretKeyRef:
                key: secret
                name: openstad-session-secret

          - name: SITE_API_KEY
            valueFrom:
              secretKeyRef:
                key: fixed_token
                name: openstad-auth-credentials

          - name: API_URL
            value: https://{{ template "openstad.api.url" . }}

          - name: APP_URL
            value: https://www.{{ .Values.host.base }}

          - name: USER_API
            value: https://{{ template "openstad.auth.url" . }}

          - name: USER_API_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: client_id
                name: openstad-auth-credentials

          - name: USER_API_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: client_secret
                name: openstad-auth-credentials

          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
                
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
        resources:
{{ toYaml .Values.admin.resources | indent 12 }}
