---
dependencies:
- name: cert-manager
  version: "0.15.1"
  repository: "https://charts.jetstack.io"

- name: mongodb
  version: "7.14.5"
  repository: "https://charts.bitnami.com/bitnami"

- name: mysql
  version: "6.14.2"
  repository: "https://charts.bitnami.com/bitnami"