
# Dependencies

dependencies:
  ## Database
  mongodb: 
    enabled: true
  mysql: 
    enabled: true

  ## SSL
  cert-manager: 
    enabled: false

# Define anchors

define:
  ## Services
  frontend:
    deploymentName: &fesDepName "frontend-deploy"
    ingressName: &fesIngName "openstad-ingress-frontend"
    serviceName: &fesName "frontend-service"
    servicePath: &fesPath /
    subdomain: &fesSubdomain 
    containerPort: &fesContainerPort 4444
    replicas: &fesReplicas 1

  auth:
    deploymentName: &asDepName "auth-deploy"
    ingressName: &asIngName "openstad-ingress-auth"
    serviceName: &asName "auth-service"
    servicePath: &asPath /oauth
    subdomain: &asSubdomain auth
    containerPort: &asContainerPort 4000
    replicas: &asReplicas 1
  
  api:
    deploymentName: &apiDepName "api-deploy"
    ingressName: &apiIngName "openstad-ingress-api"
    serviceName: &apiName "api-service"
    servicePath: &apiPath /api
    subdomain: &apiSubdomain api
    containerPort: &apiContainerPort 8111
    replicas: &apiReplicas 1
  
  image:
    deploymentName: &imgDepName "image-deploy"
    ingressName: &imgIngName "openstad-ingress-image"
    serviceName: &imgName "image-service"
    servicePath: &imgPath /img
    subdomain: &imgSubdomain img
    containerPort: &imgContainerPort 4100
    replicas: &imgReplicas 1
  
  adminer:
    deploymentName: &admDepName "adminer-deploy"
    ingressName: &admIngName "openstad-ingress-adminer"
    serviceName: &admName "adminer-service"
    servicePath: &admPath /adminer
    subdomain: &admSubdomain nil
    containerPort: &admContainerPort 80
    replicas: &admReplicas 1
  
  ## Host URLs
  host:
    host-url: &host-url www.openstad.softwaredepartment.net
    host-http: &host-http http://www.openstad.softwaredepartment.net
    host-https: &host-https https://www.openstad.softwaredepartment.net

  ## Databases
  mysql:
    username: &dbUser openstad
    password: &dbPass examplePass2146
    database: &dbName image

  mongodb:
    database: &mgdbDb openstad_mongodb

# Persistence

persistence:
  storageClassName: "hcloud-volumes"
  annotations: "{}"

# Frontend

frontend:
    replicas: *fesReplicas

    deploymentContainer:
        name: frontend-container # Originally: frontend
        image: openstad/frontend:debug # Originally: openstad/frontend:debug
        port: *fesContainerPort # Originally: 4444

    host:
        path: *fesPath
        subdomain: *fesSubdomain

    deployment:
        name: *fesDepName # Originally: frontend

    service:
        name: *fesName # Originally: frontend-service
        httpPort: *fesContainerPort
        managementPort: 9090
    
    probe:
      liveness:
        initialDelaySeconds: 30
        periodSeconds: 60

# Adminer

adminer:
  replicas: *admReplicas

  service:
    name: *admName
  deployment:
    name: *admDepName
  
  label: adminer-web

  deploymentContainer:
    name: auth
    image: adminer
    port: *admContainerPort

  probe:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 60

# Auth

auth:
  replicas: *asReplicas

  service:
    name: *asName
  deployment:
    name: *asDepName
  
  label: auth-container

  host:
    path: *asPath
    subdomain: *asSubdomain

  deploymentContainer:
    name: auth-container
    image: openstad/auth:test
    port: *asContainerPort
  
  probe:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 60

# API

api:
  replicas: *apiReplicas
  
  service:
    name: *apiName
  deployment:
    name: *apiDepName
  
  label: openstad-api

  host:
    path: *apiPath
    subdomain: *apiSubdomain

  deploymentContainer:
    name: api-container
    image: openstad/api:test
    port: *apiContainerPort

  probe:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 60

# Image

image:
  replicas: *imgReplicas
  
  service:
    name: *imgName
  deployment:
    name: *imgDepName
  
  label: image-container

  host:
    path: *imgPath
    subdomain: *imgSubdomain

  deploymentContainer:
    name: image
    image: openstad/image:test
    port: *imgContainerPort

  probe:
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 60



# Automatically configured sections

## Generic

host:
  www: *host-url
  http: *host-http
  https: *host-https

## Secrets

secrets:
  database: # SQL database
    secretName:
    image:
      secretName:
    auth:
      secretName:
      credentials:
        secretName:
    api:
      secretName:
    frontend:
      secretName:
    adminer:
      secretName:

    password: *dbPass
    username: *dbUser

  hosts:
    secretName:

  cookies:
    secretName:

  mail:
    auth:
      secretName:
    api:
      secretName:

  mongodb: # Mongo Database
    secretName:
    database: *mgdbDb

 
## TLS

tls:
  host: *host-url

## Ingress

ingress:
  adminerService:
    ingName: *admIngName
    name: *admName
    path: *admPath
    containerPort: *admContainerPort
    subdomain: *admSubdomain

  frontendService:
    ingName: *fesIngName
    name: *fesName
    path: *fesPath
    containerPort: *fesContainerPort
    subdomain: *fesSubdomain

  authService:
    ingName: *asIngName
    name: *asName
    path: *asPath
    containerPort: *asContainerPort
    subdomain: *asSubdomain
  
  apiService:
    ingName: *apiIngName
    name: *apiName
    path: *apiPath
    containerPort: *apiContainerPort
    subdomain: *apiSubdomain
  
  imageService:
    ingName: *imgIngName
    name: *imgName
    path: *imgPath
    containerPort: *imgContainerPort
    subdomain: *imgSubdomain

## Subcharts

### MongoDB overwrite subchart

mongodb:
  mongodbUsername: *dbUser
  mongodbPassword: *dbPass
  mongodbDatabase: *mgdbDb

### MySQL overwrite subchart

mysql:
  db:
    user: *dbUser
    password: *dbPass
    name: *dbName