kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  selector:
    app: auth-container
  ports:
  - name: http
    protocol: TCP
    port: 4000
  - name: management
    port: 9090
  type: ClusterIP
