---
# Previously $gitRoot/k8s/ingress/external.yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openstad-{{ .Values.frontend.name }}-ingress
  namespace: {{ .Values.frontend.namespace }}
spec:
  rules:
  - host: www.openstad.softwaredepartment.net
    http:
      paths:
      - backend:
          serviceName: {{ .Values.frontend.name }}-service
          servicePort: 4444
        path: /
  tls:
  - hosts:
    - www.openstad.softwaredepartment.net
    secretName: openstad-tls
