---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingress.imageService.ingName }}
  namespace: {{ .Release.Namespace }}
spec:
  {{ template "ingressRules" (merge (dict "service" .Values.ingress.imageService) (dict "service" .Values.host)) }}
  tls: 
  - hosts:
    - {{ (printf "*.%s" .Values.host.base) | quote }}
    secretName: {{ .Values.tls.secretName | default "openstad-tls" }}
