apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-claim
  namespace: openstad
spec:
  storageClassName: hcloud-volumes
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi