apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-data-claim
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.persistence.annotations }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-uploads-claim
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.persistence.annotations }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-data-claim
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.persistence.annotations }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
