apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistence-claim
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.persistence.annotations }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
