apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: openstad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer-web
  template:
    metadata:
      labels:
        app: adminer-web
    spec:
      containers:
      - name: auth
        image: adminer
        ports:
            - name: http
              containerPort: 8080
        env:
          # DB Reference
          - name: ADMINER_DEFAULT_SERVER
            value: "openstad-mysql"
