authVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: openstad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openstad-auth
  template:
    metadata:
      labels:
        app: openstad-auth
    spec:
      containers:
      - name: auth
        image: openstad/auth:test
        ports:
            - name: http
              containerPort: 4000



        env:
          
          # HOSTING
          - name: APP_URL
            valueFrom:
              secretKeyRef:
                name: openstad-hosts
                key: auth

          # HOSTING
          - name: ADMIN_REDIRECT_URL
           valueFrom:
             secretKeyRef:
               name: openstad-hosts
               key: frontend


                

          # MySQL DATABASE
          - name: DB_VENDOR
            valueFrom:
              secretKeyRef:
                name: openstad-db-credentials
                key: type

          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: openstad-db-credentials
                key: username

          - name: DB_PWD
            valueFrom:
              secretKeyRef:
                name: openstad-db-credentials
                key: password

          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: openstad-db-credentials
                key: hostname

          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: openstad-db-credentials
                key: hostport

          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: openstad-auth-db
                key: database




          # SMTP MAIL
          - name: MAIL_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: openstad-auth-mail
                key: host

          - name: MAIL_SERVER_PORT
            valueFrom:
              secretKeyRef:
                name: openstad-auth-mail
                key: port

          - name: MAIL_SERVER_SECURE
            value: "yes"

          - name: MAIL_SERVER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: openstad-auth-mail
                key: password

          - name: MAIL_SERVER_USER_NAME
            valueFrom:
              secretKeyRef:
                name: openstad-auth-mail
                key: user
    
          - name: EMAIL_ASSETS_URL
            valueFrom:
              secretKeyRef:
                name: openstad-auth-mail
                key: email_assets_url
    
          - name: FROM_NAME
            value: "Openstad api"
  
            - name: FROM_EMAIL
            valueFrom:
              secretKeyRef:
                name: openstad-auth-mail
                key: user




          # KUBERNETES
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                authVersion: v1
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP


        resources:
          limits:
            cpu: "0.1"
            memory: 1Gi
          requests:
            cpu: "100m"
            memory: "500M"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
      initContainers:
      - name: init-db-ready
        image: openstad/auth:test
        env:
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: openstad-db-credentials
              key: hostname
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: openstad-db-credentials
              key: hostport 
        command: ["/bin/sh","-c"]         
        args: ['TODO whatever is needed here to run database init']   
