apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: openstad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openstad-frontend
  template:
    metadata:
      labels:
        app: openstad-frontend
    spec:
      containers:
      - name: frontend
        image: openstad/frontend:test
        imagePullPolicy: Always
        ports:
            - name: http
              containerPort: 4444
        env:
          # HOST
          - name: DEFAULT_HOST
            value: "www.openstad.softwaredepartment.net"
          - name: HOST_DOMAIN
            valueFrom:
              secretKeyRef:
                name: openstad-hosts
                key: frontend
          - name: PORT
            value: "4444"
          - name: SITE_API_KEY
            valueFrom:
              secretKeyRef:
                name: openstad-auth-credentials
                key: fixed_token
          # MONGO
          - name: MONGO_DB_HOST
            valueFrom:
              secretKeyRef:
                name: openstad-mongo-credentials
                key: hostname
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: openstad-mongo-credentials
                key: hostname
          - name: DEFAULT_DB
            valueFrom:
              secretKeyRef:
                name: openstad-mongo-credentials
                key: database
          # KUBERNETES
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
          limits:
            cpu: "0.1"
            memory: 1Gi
          requests:
            cpu: "100m"
            memory: "500M"
