apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deploy
  namespace: openstad
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-container
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: image-container
    spec:
      containers:
      - env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: hostname
              name: openstad-db-credentials
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: database
              name: openstad-image-db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: openstad-db-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: openstad-db-credentials
        - name: APP_URL
          value: www.openstad.softwaredepartment.net
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: openstad/image:test
        imagePullPolicy: Always
        name: image
        ports:
        - containerPort: 4100
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 4100
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 500M
      initContainers:
      - args:
        - knex migrate:latest
        command:
        - /bin/sh
        - -c
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: database
              name: openstad-image-db
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: hostname
              name: openstad-db-credentials
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: openstad-db-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: openstad-db-credentials
        image: openstad/image:test
        imagePullPolicy: Always
        name: create-db-ready
      restartPolicy: Always
