kind: Service
apiVersion: v1
metadata:
  name: api-service
spec:
  selector:
    app: api-container
  ports:
  - name: http
    protocol: TCP
    port: 8111
  - name: management
    port: 9090
  type: ClusterIP
