---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mail.api.secretName | default "openstad-api-mail" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "apiMailSecret" . }}