apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mail.api.secretName }}
  namespace: {{ .Values.secrets.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "apiMailSecret" . }}