---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.database.api.secretName | default "openstad-api-db" }}
  namespace: {{ .Values.secrets.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "apiDbSecret" . }}