---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mail.auth.secretName | default "openstad-auth-mail" }}
  namespace: {{ .Values.secrets.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "authMailSecret" . }}