---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.database.auth.credentials.secretName | default "openstad-auth-credentials" }}
  namespace: {{ .Values.secrets.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "authCredSecret" . }}