---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.database.auth.credentials.secretName }}
  namespace: {{ .Release.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "authCredSecret" . }}