---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.database.secretName | default "openstad-db-credentials"}}
  namespace: {{ .Values.secrets.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "databaseSecret" . }}
