apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.hosts.secretName }}
  namespace: {{ .Values.secrets.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "hostsSecret" . }}