{{- define "databaseSecret" -}}
  {{ printf "type: %s" (.Values.secrets.database.type | b64enc) }}
  {{ printf "database: %s" (.Values.secrets.database.dbName | b64enc) }}
  {{ printf "hostname: %s" (.Values.secrets.database.hostname | b64enc) }}
  {{ printf "hostport: %s" (.Values.secrets.database.hostport | toString | b64enc) }}
  {{ printf "password: %s" (.Values.secrets.database.password | b64enc) }}
  {{ printf "username: %s" (.Values.secrets.database.username | b64enc) }}
{{- end }}
