---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-api-db
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  database: {{ .Values.secrets.database.api.dbName | default "api" | b64enc }}