---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-auth-credentials
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "authCredSecret" . }}