---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-hosts
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  api: {{ .Values.secrets.hosts.api | default (printf "%s.%s.svc.cluster.local" .Values.api.name .Release.Namespace) | b64enc }}
  auth: {{ .Values.secrets.hosts.auth | default (printf "%s.%s.svc.cluster.local" .Values.auth.name .Release.Namespace) | b64enc }}
  frontend: {{ .Values.secrets.hosts.frontend | default (printf "%s.%s.svc.cluster.local" .Values.frontend.name .Release.Namespace) | b64enc }}
  image: {{ .Values.secrets.hosts.image | default (printf "%s.%s.svc.cluster.local" .Values.image.name .Release.Namespace) | b64enc }}
