---
{{ if .Values.dependencies.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "mysql-secret"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  {{ template "mysqlSecret" . }}
{{ end }}
